databaseChangeLog:
  - changeSet:
      id: 1724516595129-1
      author: DenisWm
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_legal_process
                  name: id
                  type: VARCHAR(36)
              - column:
                  constraints:
                    nullable: false
                  name: number
                  type: VARCHAR(25)
              - column:
                  constraints:
                    nullable: false
                  name: status
                  type: VARCHAR(12)
            tableName: legal_process

