version: '3.7'

services:
  db:
    container_name: postgresql-pol-promad
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adm_processos
    ports:
      - 5432:5432
    networks:
      - adm_processos_network
  app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - adm_processos_network
networks:
  adm_processos_network: